Fixing a few bugs and typos. (#62)
* Fixing a typo in setup script causing cemu command to fail running.

* Fixing 'Qt' has nos attribute 'red' anymore.

* Fixing: AttributeError: type object 'QTextFormat' has no attribute 'FullWidthSelection'

* keystone-engine is missing from the dependencies.