Add templates for Issues, PR and stalebot configuration file (#68)
* First commit for 0.6:
- moved to qt6
- moved python >= 3.8
- added some gh actions

* [cd] typo in `cd.yml`

* more migration to pyqt6

* updated readme.rst

* `cd` & `ci` fixes

* Update notify.yml

* Fix link to Unicorn

* Update README.md

* Update notify.yml

* back to dev, one extra step towards 0.6

* Fixing a few bugs and typos. (#62)

* Fixing a typo in setup script causing cemu command to fail running.

* Fixing 'Qt' has nos attribute 'red' anymore.

* Fixing: AttributeError: type object 'QTextFormat' has no attribute 'FullWidthSelection'

* keystone-engine is missing from the dependencies.

* more bugfix, almost stable

* cleaned `utils.py`

* yay it works again

* no need for metaclass with typing

* fix module import in `arch`

* using a proper callback system for logging

* - fixed typing issues
- [main] fixed more linting errors

* - plugins structure was revisited, more flexible

* - updated file menu

* fixed all remaining errors from `ui.main`

* updated `emulator.py`

* created a global backend context structure

* moved most of the code to use the global context

* fixed `ui.command.py` shortcuts

* moved plugins to `dockable_widgets` so they cna be hidden from control bar

* fixed emulation

* added focus mode (ctrl+f)

* kicking off 0.7

* added stale config

* added issue templates

* added PR template

Co-authored-by: Piotr Kasprzyk <ciri@ciri.pl>
Co-authored-by: thelumberjhack <5294889+thelumberjhack@users.noreply.github.com>